Add RegExp methods
web-platform-dx/web-features pull request #1565
Opened 2024-08-08 17:05 UTC by petele

2024-08-08 17:06 UTC, petele commented on features/regexp.yml
> +  - javascript.builtins.RegExp.compile
this method is deprecated - should we drop it from this list?

2024-08-08 17:06 UTC, petele commented on features/regexp.yml
> +  - javascript.builtins.RegExp.input
this method is deprecated - should we drop it from this list?

2024-08-12 15:41 UTC, ddbeck requested changes

2024-08-12 15:41 UTC, ddbeck commented on features/regexp.yml
> +description: The RegExp object is used for matching text with a regular expression.
Feature names are sentence case and also-known-as text goes in the description (if needed, though not in this case)

```suggestion
name: Regular expressions
description: The `RegExp` object represents a regular expression, a notation for matching text patterns.
```

2024-08-12 15:41 UTC, ddbeck commented on features/regexp.yml
> +  - javascript.builtins.RegExp.@@split
We also need `javascript.grammar.regular_expression_literals` and all of the non-deprecated `javascript.regular_expressions.*` keys. It's possible there are some distinct features in there, but it'll be easier to pick them out with the dist file.

2024-08-13 14:27 UTC, petele commented
Added additional keys, and removed all deprecated functions.

2024-08-13 14:31 UTC, ddbeck approved these changes
Thank you, Pete!

2024-08-13 14:31 UTC, merged