Add WebGL1 Canvas Context
web-platform-dx/web-features pull request #1583
Opened 2024-08-13 18:28 UTC by petele

Replaces #1515

2024-08-14 08:58 UTC, captainbrosset commented
I'm a bit unsure about the level of granularity here, and this is probably due to the fact that I don't know WebGL well enough. @petele @ddbeck @foolip what are your thoughts on the proposed features here?

For example, does "WebGL 32-bit floating-point color buffers" need to be its own feature? How about "Color management for WebGL"?

Are these sufficiently distinct from using WebGL? Do they allow developers to achieve a specific task? Or are they just part of how you use WebGL?

The concern I have with this is going too granular and departing from the notion of "features" which we want to be more relatable to developers than what BCD provides.

2024-08-14 10:30 UTC, dji1admin approved these changes

2024-08-14 11:36 UTC, petele commented
@foolip, @ddbeck, and I have been going back and forth on these a whole bunch and have already merged a number of items into the main 'feature'. I get the concern about too many features, but the remaining features are each something that allows a specific functionality beyond the scope of general WebGL.

2024-08-14 12:11 UTC, captainbrosset commented
Ok. Then I guess that's fine.

2024-08-16 15:03 UTC, ddbeck requested changes

2024-08-16 16:05 UTC, petele commented on features/webgl-color-buffer-float.yml
> +name: WebGL 32-bit floating-point color buffers
done

2024-08-19 12:32 UTC, ddbeck approved these changes

2024-08-19 12:47 UTC, merged