Add Symbol
web-platform-dx/web-features pull request #1669
Opened 2024-08-26 12:29 UTC by Elchi3

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol

I've used `compute_from` as the late-additions are all baseline high for quite a while as well and probably not too exciting (anymore) for them to be their own features.

2024-09-06 09:49 UTC, autonome requested changes

2024-09-06 09:49 UTC, autonome commented on features/symbol.yml
> +description: The `Symbol` type represents a unique identifier.
Heh, super abstract concept, but seems like this could use either more descriptiveness or an example, or both.

2024-09-11 09:17 UTC, Elchi3 commented on features/symbol.yml
> +description: The `Symbol` type represents a unique identifier.
```suggestion
description: The `Symbol` type is used for unique property keys – a symbol never clashes with any other property key (symbol or string).
```
```suggestion
description: The `Symbol` type represents a unique identifier.
```

2024-10-09 18:42 UTC, ddbeck approved these changes
I want to get this in today, so I'm going to merge this and open a PR with my own description suggestion. 🙂

2024-10-09 18:43 UTC, merged