Add border, border-radius and outline
web-platform-dx/web-features pull request #1794
Opened 2024-09-17 20:14 UTC by jamesnw

The caniuse for [outline](https://caniuse.com/outline) was just a bit too far off, with none of the features lining up with what I am seeing there.

2024-09-24 11:54 UTC, ddbeck requested changes
I have some thoughts on outlines, but I like the rest of this as it is.

2024-09-24 11:54 UTC, ddbeck commented on features/border-radius.yml
> +caniuse: border-radius
Let's `compute_from: css.properties.border-radius` to better align with caniuse.

2024-09-24 11:54 UTC, ddbeck commented on features/outlines.yml
> +  compute_from: css.properties.outline-style
I think it's a bit weird for us to name `outline` as the entry point to this feature, yet say that it's supported before the thing we name in the description exists. I think we have three options here (in order of my uninformed feeling about it):

1. `compute_from` on the constituent properties (`outline-color`, `-offset`, etc.) and change the description to match.
2. Break out `outline` into its own feature.
3. Drop the `compute_from` and say that outlines are a recent feature.

2024-09-24 11:54 UTC, ddbeck commented on features/outlines.yml
> +spec: https://drafts.csswg.org/css-ui-4/#outline
It'd be nice to leave a `TODO` comment here saying we _could_ reference https://caniuse.com/outline but the differences in support need reconciliation.

2024-09-24 15:19 UTC, merged

2025-02-24 21:27 UTC, RByers commented
> The caniuse for [outline](https://caniuse.com/outline) was just a bit too far off, with none of the features lining up with what I am seeing there.

FWIW I think caniuse was actually right here and BCD is wrong about outline. Filed [this bug to correct BCD](https://github.com/mdn/browser-compat-data/issues/26045)