Add features for VTTCue constructor and settings
web-platform-dx/web-features pull request #1818
Opened 2024-09-20 12:43 UTC by queengooborg

This PR creates two new features for the WebVTT API.  These two features were originally suggested as comments in the `webvtt` feature, so this PR does just that!

2024-11-22 10:56 UTC, Elchi3 commented
I opened https://github.com/web-platform-dx/web-features/pull/2310 to deal with the constructor

2024-11-22 14:50 UTC, autonome requested changes
Suggested couple of fixes, but looks good otherwise w/ these addressed!

2024-11-22 14:50 UTC, autonome commented on features/webvtt-cue-settings.yml
> +description: The members of the `VTTCue` API can be used to update cues dynamically.
```suggestion
description: The `VTTCue` API updates various aspects of cues dynamically, such as alignment, size and position.
```

2024-11-22 14:50 UTC, autonome commented on features/webvtt-cue-settings.yml
> +name: WebVTT Cue Settings
```suggestion
name: WebVTT cue settings
```

2024-11-25 16:35 UTC, jamesnw commented
Should this feature also include `css.selectors.cue` and `css.selectors.cue.selector_argument`?

2024-11-26 10:41 UTC, Elchi3 commented
> Should this feature also include `css.selectors.cue` and `css.selectors.cue.selector_argument`?

Added along with a compute_from.

2024-11-26 11:06 UTC, autonome approved these changes

2024-11-26 11:10 UTC, merged