Add feature for Geometry Interfaces Module Level 1
web-platform-dx/web-features pull request #1837
Opened 2024-09-25 01:21 UTC by queengooborg

This PR adds a feature for the Geometry Interfaces Module Level 1.

2024-10-07 14:39 UTC, ddbeck requested changes
I think the key question here is: what APIs actually return these types today?

I'm having a hard time reviewing this feature because it reads as extremely generic and I can't find any developers actually talking about "geometry level 1." As written, this feature tells a very unlikely story: that browsers shipped—and developers want—an abstract facility for doing geometry math.

The spec (and searching Stack Overflow) hints that this is not really case:

> The SVG interfaces [SVGPoint](https://drafts.fxtf.org/geometry/#svgpoint), [SVGRect](https://drafts.fxtf.org/geometry/#svgrect) and [SVGMatrix](https://drafts.fxtf.org/geometry/#svgmatrix) are aliasing the here defined interfaces in favor for common interfaces used by SVG, Canvas 2D Context and CSS Transforms. [[SVG11]](https://drafts.fxtf.org/geometry/#biblio-svg11) [[HTML]](https://drafts.fxtf.org/geometry/#biblio-html) [[CSS3-TRANSFORMS]](https://drafts.fxtf.org/geometry/#biblio-css3-transforms)

I don't know what the oldest thing is here but due to the limitations that we need to resolve in https://github.com/web-platform-dx/web-features/issues/971, I suspect these keys should (for now) reside with their oldest companion features, probably something like SVG or Canvas.

2024-10-07 15:55 UTC, dontcallmedom commented
> I think the key question here is: what APIs actually return these types today?

see e.g. https://dontcallmedom.github.io/webidlpedia/names/DOMMatrix.html (section "Methods and attributes that return objects implementing DOMMatrix") - works for other names in the list as well.

> I'm having a hard time reviewing this feature because it reads as extremely generic and I can't find any developers actually talking about "geometry level 1.

+1

> I don't know what the oldest thing is here but due to the limitations that we need to resolve in #971, I suspect these keys should (for now) reside with their oldest companion features, probably something like SVG or Canvas.

[Historically](https://www.w3.org/TR/2013/WD-matrix-20130919/), 
> The transformation matrix interface replaces the SVGMatrix interface from SVG1.1

Among different usages, `SVGMatrix` was the type for the long-supported [ `SVGTransform.matrix`](https://developer.mozilla.org/en-US/docs/Web/API/SVGTransform)

2024-11-21 15:26 UTC, Elchi3 commented on features/geometry.yml
> +name: Geometry Level 1
```suggestion
name: Geometric shapes
```

2024-11-21 15:26 UTC, Elchi3 commented on features/geometry.yml
> +description: The Geometry interfaces offer a way to represent points, rectangles, quadrilaterals and transformation matrices within JavaScript.
```suggestion
description: The `DOMMatrix`, `DOMPoint`, `DOMQuad` and `DOMRect` interfaces offer a way to represent points, rectangles, quadrilaterals and transformation matrices within JavaScript. They can be used in transformations in CSS, `<canvas>`, and SVG.
```

2024-11-22 11:19 UTC, Elchi3 commented
I've updated name and description here. I think this is part of the DOM and is an abstract set of interfaces that serve multiple other APIs such as CSS, canvas and SVG. Developers will encounter it in these contexts and if they have worked with it in say CSS, it will be familiar in SVG or canvas. I think it is fine to have such abstract features. Array is also abstract in that sense. I think Python doesn't have builtin matrices either and so numpy is an abstract package ("feature") which will let you work with matrices as a general thing. Does all this move us forward in some direction with this PR?

2024-12-17 10:48 UTC, Elchi3 commented
I discussed this with @ddbeck and we think landing this as "DOM Geometry" is best.

2024-12-17 10:56 UTC, ddbeck approved these changes
Thank you!

2024-12-17 10:56 UTC, merged