Add feature for CSS Font Loading API
web-platform-dx/web-features pull request #1838
Opened 2024-09-25 01:33 UTC by queengooborg

This PR adds a feature for the CSS Font Loading API.

2024-09-25 15:07 UTC, jamesnw requested changes
Nice feature! A few small suggestions.

2024-09-25 15:07 UTC, jamesnw commented on features/font-loading.yml
> +name: CSS Font Loading
```suggestion
name: Font loading
```
The common name here is "CSS Font Loading API", which makes me grumpy as it's a JS API for loading fonts, which are used in CSS. I think we should either remove "CSS" or keep the whole name, including API.

2024-09-25 17:38 UTC, jamesnw approved these changes
This is looking good to me!

2024-09-27 10:43 UTC, ddbeck approved these changes

2024-09-27 10:43 UTC, ddbeck commented on features/font-loading.yml
> +description: The CSS Font Loading API dynamically loads custom fonts and tracks when fonts are loading or ready to use.
I'm going to apply this to be able to merge today, but for posterity:

Prefer an essential entry point to an API over a spec name. It's much more concrete and directly connects with what a developer does with this feature.

```suggestion
description: The `document.fonts` API dynamically loads custom fonts and tracks when fonts are loading or ready to use.
```

2024-09-27 10:44 UTC, merged