Add console as a feature
web-platform-dx/web-features pull request #1839
Opened 2024-09-25 02:49 UTC by queengooborg

This PR adds the console interface as a feature.

2024-09-25 13:24 UTC, captainbrosset requested changes

2024-09-25 13:24 UTC, captainbrosset commented on features/console.yml
> +description: To write...
```suggestion
description: The `console` API logs debugging messages to the browser development tools' console.
```

2024-09-25 13:24 UTC, captainbrosset commented on features/console.yml.dist
> +  - api.console.profileEnd_static
BCD says that `profile` was removed in Firefox in 102. But BCD also says that `profileEnd` didn't get the same treatment, and that seems like a BCD bug to me. I would expect both to either be present or not.
In fact, both are defined for me in Firefox Nightly right now.

2024-09-27 13:41 UTC, captainbrosset commented on features/console.yml.dist
> +  - api.console.profileEnd_static
I see you've removed `profile` but left `profileEnd`. I guess we should instead either have them both in, or out. In this case, I think this is more likely a BCD bug. When I tested quickly, both functions seemed available in Firefox.

2024-09-28 07:38 UTC, captainbrosset approved these changes
I think this is good to merge as is, but we need to do something about profile/profileEnd, I'd suggest opening a BCD issue to investigate if the Firefox support data needs to be updated.

2024-10-09 14:08 UTC, Elchi3 commented
I opened https://github.com/mdn/browser-compat-data/pull/24675

2024-10-09 14:12 UTC, merged