Add feature for the Battery Status API
web-platform-dx/web-features pull request #1840
Opened 2024-09-25 03:28 UTC by queengooborg

This PR adds a feature for the Battery Status API.

2024-09-25 13:25 UTC, captainbrosset submitted a review, later dismissed

2024-09-25 13:25 UTC, captainbrosset commented on features/battery.yml
> +name: Battery Status
```suggestion
name: Battery status
```

2024-09-25 13:25 UTC, captainbrosset commented on features/battery.yml
> +description: The Battery Status API allows web developers to obtain information about the device's battery, including charge level and status.
```suggestion
description: The `navigator.getBattery()` API obtains information about the device's battery, including charge level and status. Also known as the Battery API.
```

2024-09-25 19:20 UTC, ddbeck requested changes

2024-09-25 19:20 UTC, ddbeck commented on features/battery.yml
> +spec: https://w3c.github.io/battery/
```suggestion
spec: https://w3c.github.io/battery/
caniuse: battery-status
```

2024-09-25 19:20 UTC, ddbeck commented on features/battery.yml
> +  compute_from: api.BatteryManager
This is not wrong exactly but, in general, prefer `compute_from` values that are the most-essential entry point(s) to the feature, what a developer would actually have to type to use it. Here that's the `navigator` API, not the `BatteryManager` interface.

(The exception is when you need to align with caniuse—where you'd use the minimal set of keys to achieve that, assuming the entry point is not sufficient—but that's not needed here.)

```suggestion
  compute_from: api.Navigator.getBattery
```

2024-09-26 15:47 UTC, ddbeck approved these changes

2024-09-26 15:47 UTC, merged