add history
web-platform-dx/web-features pull request #1902
Opened 2024-10-04 07:35 UTC by autonome

2024-10-04 12:55 UTC, captainbrosset requested changes

2024-10-04 12:55 UTC, captainbrosset commented on features/history.yml.dist
> +  - api.History.pushState
This is the support data that matches caniuse.com. So, it seems like everything up to this point is really necessary to use the API, but the 2 following keys are nice-to-haves (`state` and `scrollRestoration`). Reading their documentation, it does seem like you can use the API without them.
So I would be tempted to use `compute_from` on `api.History.pushState` to match caniuse.com.

2024-10-04 12:55 UTC, captainbrosset commented on features/history.yml
> +description: "The History API allows manipulation of the browser session history, from navigations to state management, in the tab or frame that the current page is loaded in."
```suggestion
description: "The History API manipulates the browser session history, from navigations to state management, in the tab or frame that the current page is loaded in."
```

2024-10-04 15:07 UTC, jamesnw approved these changes
Approved pending changes from @captainbrosset

2024-10-05 03:38 UTC, autonome commented on features/history.yml
> +description: "The History API allows manipulation of the browser session history, from navigations to state management, in the tab or frame that the current page is loaded in."
the curse of the passive voice!

2024-10-07 03:38 UTC, autonome commented
Implemented @captainbrosset's changes, and dismissing review for merge. Github review flow isn't great for the "r+ w/ changes addressed" approach.

2024-10-07 03:39 UTC, merged