Add Window and Window Management API
web-platform-dx/web-features pull request #2010
Opened 2024-10-21 06:36 UTC by autonome

2024-11-12 07:34 UTC, autonome commented
>   # baseline: false
>   # support:
>   #   chrome: "1"
>   #   chrome_android: "18"
>   #   edge: "12"
>   #   firefox: "1"
>   #   firefox_android: "4"
>   #   safari: "1"
>   - api.Window.open

hmm need to check this out

2024-11-14 09:20 UTC, Elchi3 commented
BCD has partial_implementation for window.open https://github.com/mdn/browser-compat-data/blob/85134660ebd65ba1ff2d2561f24fa81ddbbc6619/api/Window.json#L3378

2024-11-18 13:01 UTC, autonome commented
@ddbeck I'm reluctant to call this not baseline high for the `window.open` issue. That API has been around since the dawn of the web. Outside of that issue, should be ready for review here.

2024-11-18 13:52 UTC, ddbeck requested changes
A few suggestions for you. This is pretty close though.

2024-11-18 13:52 UTC, ddbeck commented on features/dialog.yml
> +  - api.Window.prompt
It's unclear to me how these relate to `<dialog>` element (except that they produce modals). I think you should drop these from this PR and pick it up as a separate feature.

2024-11-18 13:52 UTC, ddbeck commented on features/dialog.yml
> +  - css.selectors.backdrop.dialog
I think this key belongs in `backdrop.yml`, given that it's the example use-case for that feature.

2024-11-18 13:52 UTC, ddbeck commented on features/history.yml
> +  - api.Window.history
Can you update the description for this feature to mention that this is the entry point?

> "The `window.history` API manipulates the browser session history…

2024-11-18 13:52 UTC, ddbeck commented on features/window-management.yml
> +name: Window Management
[Sentence casing](https://github.com/web-platform-dx/web-features/blob/main/docs/guidelines.md#names), please

```suggestion
name: Window management
```

2024-11-18 13:52 UTC, ddbeck commented on features/window-management.yml
> +description: "The Window Management API makes it possible to build multi-screen applications by providing access to information about the screens on a device, and to place content on a specific scree
More concretely, I think we could say something like:

```suggestion
description: "The `window.getScreenDetails()` method gets information about the screens on a device, which you can use to place new windows on a specific screen with `window.open()`.
```

2024-11-18 13:52 UTC, ddbeck commented on features/window.yml
> +  - api.Window.originAgentCluster
I think this is a separate thing (with `Origin-Agent-Cluster`) that you can drop from this PR.

2024-11-18 13:52 UTC, ddbeck commented on features/window.yml
> +  - api.Window.rejectionhandled_event
I suspect this belongs with `promises`. You can drop it from this PR.

2024-11-18 13:52 UTC, ddbeck commented on features/window.yml
> +  - api.Window.unhandledrejection_event
I suspect this belongs with `promises`. You can drop it from this PR.

2024-11-18 13:52 UTC, ddbeck commented on features/window.yml
> +description: "The Window object is home to a variety of functions, namespaces, objects, and constructors. Some of these are associated with the user interface window the document is loaded in, but ma
To create some symmetry with the `navigator` feature you created previously:

```suggestion
description: "The `window` global object represents a browser tab or iframe and its relationship to the document and other tabs. It's also a generic global object, under which many other APIs are located."
```

2024-11-18 13:52 UTC, ddbeck commented on features/window.yml
> +  - api.Window.document
This could belong in `dom.yml`. Here's fine, but this is yet another case where overlapping keys would be nice.

2024-11-18 15:57 UTC, autonome commented
Thanks for review, fixes applied!

2024-11-18 16:21 UTC, merged