Add more keys to OPFS
web-platform-dx/web-features pull request #2053
Opened 2024-10-23 09:57 UTC by Elchi3

This was originally added here: https://github.com/web-platform-dx/web-features/pull/1033 and it had a bunch of later additions in comments (which then got lost as we migrated to BCD tags).

Compare with the latest draft file: https://github.com/web-platform-dx/web-features/blob/main/features/draft/spec/fs.yml

I'm not sure if the correct way forward here is to use `compute_from `or to split some of this out to a new feature. Help appreciated.

2024-10-23 10:50 UTC, captainbrosset commented
I think these keys need to go into the `file-system-access` feature instead.

The File System Access API is more general than OPFS. In a way, OPFS is one _implementation_ of the File System Access API, or rather, one way to use it.

The entry point for OPFS is `navigator.storage.getDirectory()` which gives you access to a directory where you can then read/write/manipulate directories and files, just like you would with the File System Access API. **But** this directory is per origin only, and the browser can choose to implement it any way it likes (including without using real files on disk).

File System Access API, in contrast, gives you access to the real files and folders on disk, and therefore multiple origins can access the same files if the user allows it.

I think we need to keep all of the filesystem handle interface stuff in the more general File System Access API feature, and leave OPFS mostly focused on the getDirectory method.

2024-10-29 14:19 UTC, captainbrosset requested changes

2024-10-29 14:19 UTC, captainbrosset commented on features/file-system-access.yml
> +  - api.FileSystemSyncAccessHandle.truncate.sync_version
After some more reading, it seems like these `FileSystemSyncAccessHandle` things are just for OPFS.

MDN says this: 

> This class is only accessible inside dedicated [Web Workers](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API) [...] for files within the [origin private file system](https://developer.mozilla.org/en-US/docs/Web/API/File_System_API/Origin_private_file_system), which is not visible to end-users.

So I believe we should move these 4 keys to the OPFS feature instead.

2024-10-29 15:03 UTC, closed without merging

2024-10-29 15:08 UTC, Elchi3 commented
hm, I hit the wrong command here. Meant to force push but deleted the branch instead 😢 
Seems like I can't come back to this PR, so please see https://github.com/web-platform-dx/web-features/pull/2104