Add alerts, new window keys
web-platform-dx/web-features pull request #2273
Opened 2024-11-19 11:21 UTC by autonome

2024-11-19 13:09 UTC, ddbeck requested changes

2024-11-19 13:09 UTC, ddbeck commented on features/window.yml
> +  - api.Window.open.features_parameter_attributionsrc
This is part of the attribution reporting API. Leave this key out.

2024-11-19 13:09 UTC, ddbeck commented on features/window.yml
> +  - api.Window.open.relative-multi-screen
This belongs with the window-management feature.

2024-11-19 17:35 UTC, autonome commented on features/permissions.yml
> +status:
Erp, not meant for this PR, reverting.

2024-11-20 13:31 UTC, ddbeck approved these changes

2024-11-20 13:31 UTC, merged