Add more media keys and features
web-platform-dx/web-features pull request #2351
Opened 2024-11-27 14:08 UTC by autonome

2025-01-13 17:28 UTC, ddbeck requested changes
Several suggestions here, but nothing earth shattering. Thank you!

2025-01-13 17:28 UTC, ddbeck commented on features/media-capture-region.yml
→ `region-capture.yml`

(to match the name)

2025-01-13 17:28 UTC, ddbeck commented on features/media-playback-quality.yml
> +description: The Media Playback Quality API contains metrics that can be used to determine the playback quality of a video, such as the creation time, and how many frames were dropped.
```suggestion
description: The `getVideoPlaybackQuality()` method of `HTMLVideoElement` returns metrics that can be used to determine the playback quality of a video, such as how many frames were dropped.
```

2025-01-13 17:28 UTC, ddbeck commented on features/media-recording.yml
> +description: The MediaStream Recording API captures the data generated by a `MediaStream` or `HTMLMediaElement` object for analysis, processing, or saving to disk. It's also known as the Media Record
```suggestion
description: The `MediaRecorder` API captures data generated by `MediaStream` or `HTMLMediaElement` objects for analysis, processing, or saving to disk. Also known as the Media Recording API or the MediaRecorder API.
```

2025-01-13 17:28 UTC, ddbeck commented on features/media-recording.yml
→ `mediastream-recording.yml`

(to match up with the name)

2025-01-13 17:28 UTC, ddbeck commented on features/media-transform.yml
> +name: MediaStreamTrack insertable media processing using streams
This seems to be more common (e.g., on MDN and developer.chrome.com)

```suggestion
name: Insertable streams for MediaStreamTrack
```

2025-01-13 17:28 UTC, ddbeck commented on features/media-transform.yml
→ `insertable-streams.yml`

(to align with the name below)

2025-01-13 17:28 UTC, ddbeck commented on features/media-transform.yml
> +description: The MediaStreamTrack Insertable Media Processing using Streams API, also known as MIMPuS, gives direct access to media streams for manipulations such as merging streams, real time effect
If the spec is going to lead with funny hats, then I think we should too:

```suggestion
description: The `MediaStreamTrackProcessor` and `MediaStreamTrackGenerator` APIs modify the contents of a media track for merging streams, applying real-time effects like funny hats, and content overlays.
```

2025-01-15 00:35 UTC, autonome commented on features/media-capabilities.yml
> +  compute_from: api.MediaCapabilities
Just this key, all its subkeys, or merge the whole feature?

Media properties encoding/decoding/bitrate/etc seems orthogonal to whether it's encrypted or not.

2025-01-15 21:09 UTC, autonome commented on features/media-capabilities.yml
> +  compute_from: api.MediaCapabilities
Got it! Moved, but still had to keep the computed status b/c of a different key in there.

2025-01-16 09:00 UTC, ddbeck approved these changes

2025-01-16 09:00 UTC, merged