Add SVG deprecated as discouraged feature
web-platform-dx/web-features pull request #2485
Opened 2024-12-20 19:03 UTC by jamesnw

2024-12-20 19:16 UTC, jamesnw reviewed
Additional context- https://github.com/w3c/svgwg/wiki/SVG-2-new-features#removed

2024-12-20 19:16 UTC, jamesnw commented on features/ping.yml
> -  compute_from: html.elements.a.ping
This was added to hide the deprecated SVG elements, and so it can be removed.

2024-12-20 19:16 UTC, jamesnw commented on features/svg-deprecated.yml
> +description: SVG 2 deprecated or removed a significant number of features defined in SVG 1.1, including features related to fonts, alternate glyphs, the `xlink` namespace, and the `<cursor>` and `<tr
This was a bit difficult to write, as this is a junk drawer feature, and its entire purpose for existing is to describe that deprecations occurred, and not the features themselves.

2024-12-20 19:16 UTC, jamesnw commented on features/svg-deprecated.yml
> +    - https://svgwg.org/svg2-draft/changes.html#substantial
Rather than link to the individual parts that deprecate each feature, this link enumerates them for us.

2024-12-20 19:16 UTC, jamesnw commented on features/svg.yml
> -  - svg.elements.script.xlink_href
Will be marked as deprecated in https://github.com/mdn/browser-compat-data/pull/25477, but that doesn't block this change.

2025-01-06 15:03 UTC, jamesnw commented on features/svg.yml
> -  - svg.elements.script.xlink_href
This will be resolved in #2500

2025-01-06 16:31 UTC, ddbeck requested changes
Thanks for this @jamesnw. I'm not sure how much (if any) time you'll be spending on this stuff in this calendar year, so I've made some suggestions. It looks like I'll catch up with you tomorrow and we can make a plan for handling the follow up work here.

2025-01-06 16:31 UTC, ddbeck commented on features/svg-deprecated.yml
> +description: SVG 2 deprecated or removed a significant number of features defined in SVG 1.1, including features related to fonts, alternate glyphs, the `xlink` namespace, and the `<cursor>` and `<tr
OK, this took a bit of digging, but I think I now have a better idea of how to represent this.

In general, I think we should talk about SVG 1.1 as having some now-discouraged facets. This is a bit awkward, but I think it's a lit bit more in the spirit of describing a "feature" rather than a "change."

(Another approach here would be to break this into pieces, describing each thing as a feature—but that's a lot of work for an audience that probably does not exist. I think we should go ahead and make this a junk drawer feature, holding open the possibility of splitting this up in the future.)

While we're here, I think we should ignore two pieces, both of which will be eligible for removal from BCD in less than three weeks:

- `<tref>`
- `<cursor>`

```suggestion
name: SVG 1.1 (discouraged)
description: The SVG 1.1 image format has several components that were excluded from SVG 2, such as fonts, alternate glyphs, and the `xlink` namespace.
```

2025-01-06 16:31 UTC, ddbeck commented on features/svg-deprecated.yml
>  compat_features:
I can't suggest on the stuff outside the diff, but I propose dropping the keys relating to `<tref>` and `<cursor>`.

2025-01-06 18:50 UTC, jamesnw commented on features/ping.yml
>    - html.elements.area.ping
Hmm- you're right. I'm not remembering how they got sorted into the deprecated ones. I'll revert that portion.

2025-01-06 18:50 UTC, jamesnw commented on features/svg-deprecated.yml
> +description: SVG 2 deprecated or removed a significant number of features defined in SVG 1.1, including features related to fonts, alternate glyphs, the `xlink` namespace, and the `<cursor>` and `<tr
This makes sense to me, and I agree the audience is likely not there for splitting them up.

2025-01-07 11:57 UTC, ddbeck approved these changes
Thank you, @jamesnw!

2025-01-07 11:57 UTC, merged