Discouraged CSS features
web-platform-dx/web-features pull request #2486
Opened 2024-12-20 19:29 UTC by jamesnw

Credit to @vwallen for the content.

2025-01-06 16:31 UTC, captainbrosset approved these changes
Approved with a suggestion for the missing description.

2025-01-08 17:26 UTC, ddbeck requested changes
Some ideas here, mostly to avoid having to stuff discouraged information into the IDs and descriptions.

2025-01-08 17:26 UTC, ddbeck commented on features/overflow-overlay.yml
> +description: "The `overflow: overlay` CSS declaration sets the behavior for when content doesn't fit in an element. It is superceded by `overflow: auto`."
Yikes, this one is messy. According to https://caniuse.com/css-overflow-overlay, this has a rather different between versions that BCD doesn't capture at all. I suspect what this needs is new support statements in BCD, showing `partial_implementation` when browsers had the non-standard behavior (i.e., before they aliased to `auto`).

Maybe we thread this needle like this:

```suggestion
description: "The `overflow: overlay` CSS declaration is an alias to `overflow: auto`. However, non-standard historic implementations change the appearance of scrollbars when content doesn't fit in an element."
```

And then keep this whole file in `drafts` until we (I?) can do the work upstream.

(cc: @atopal this is another good example of a "feature" that is interoperable—`overflow: overlay` aliasing to `overflow: auto`—but a bad thing to describe as Baseline)

2025-01-08 17:26 UTC, ddbeck commented on features/text-decoration-line-blink.yml
> +description: "The deprecated `text-decoration: blink` CSS declaration used to make text alternate between being visible and invisible."
Let's write these in the usual way (present-tense, not incorporating the "deprecation"):

```suggestion
description: "The `text-decoration: blink` CSS declaration flashes text between visible and invisible."
```

2025-01-08 17:26 UTC, ddbeck commented on features/word-break-break-word.yml
> +description: "The `word-break: break-word` CSS declaration sets word breaks to occur according to their customary rules. It is superceded by `overflow-wrap: anywhere`"
I think this is more inline with our "not to be confused with" and "also known as". I suspect we'll soon need a style guide entry for these.

```suggestion
description: "The `word-break: break-word` CSS declaration sets word breaks to occur according to their customary rules. Superseded by `overflow-wrap: anywhere`"
```

2025-01-08 17:26 UTC, ddbeck commented on features/writing-mode-deprecated.yml
> +description: The `lr`, `lr-tb`, `rl`, `rl-tb`, `tb`, and `tb-rl` keyword values represent writing modes for elements in SVG 1.1 documents.
Let's line this up closer to the other writing-mode features

```suggestion
name: writing-mode SVG 1.1 values
description: The `lr`, `lr-tb`, `rl`, `rl-tb`, `tb`, and `tb-rl` keyword values for the `writing-mode` CSS property set the text direction for elements in SVG 1.1 documents.
```

2025-01-08 17:26 UTC, ddbeck commented on features/writing-mode-deprecated.yml
`features/writing-mode-deprecated.yml` → `features/writing-mode-svg-values.yml`

2025-01-09 18:14 UTC, ddbeck approved these changes
One last nit, but this is ready to merge at your convenience.

2025-01-09 18:14 UTC, ddbeck commented on features/word-break-break-word.yml
> +description: "The `word-break: break-word` CSS declaration sets word breaks to occur according to their customary rules. Superseded by `overflow-wrap: anywhere`"
```suggestion
description: "The `word-break: break-word` CSS declaration sets word breaks to occur according to their customary rules. Superseded by `overflow-wrap: anywhere`."
```

2025-01-16 08:56 UTC, ddbeck requested changes

2025-01-16 08:56 UTC, ddbeck commented on features/overflow-overlay.yml
> +description: "The `overflow: overlay` CSS declaration sets the behavior for when content doesn't fit in an element. It is superceded by `overflow: auto`."
After doing the work on the compat data, I'm now suggesting:

```suggestion
description: "The `overflow: overlay` CSS declaration is an alias to `overflow: auto`. Historically, it caused non-standard behavior, allowing scrollbars to overlay content without taking up layout space."
```

2025-01-16 17:17 UTC, merged